services:
  lukeblaney.co.uk:
    build: .
    container_name: lukeblaney.co.uk
    ports:
      - $PORT:80
    image: lucas42/lukeblaney.co.uk
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:80/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
