version: '3'
name: lukeblaney_co_uk
services:
  lukeblaney.co.uk:
    build: .
    container_name: lukeblaney.co.uk
    ports:
      - "8021:80"
    image: lucas42/lukeblaney.co.uk
    restart: always
